# Generated by Django 5.1.5 on 2025-01-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_controller', '0002_profile_avatar_profile_portfolio_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='competencies',
            field=models.ManyToManyField(related_name='sessions_set', through='session_controller.SessionCompetency', to='session_controller.competency'),
        ),
        migrations.AddField(
            model_name='sessioncompetency',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessioncompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_sessions', to='session_controller.competency'),
        ),
        migrations.AlterField(
            model_name='sessioncompetency',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_competencies', to='session_controller.session'),
        ),
    ]
